github: https://github.com/JungHanYoung

# Site
repository: JungHanYoung/resume
favicon: images/favicon.ico

# Personal info
name: 정한영
title: 백엔드 개발자 포트폴리오
email: 8735132@gmail.com
website: www.github.com/JungHanYoung

# Social links
github_username: JungHanYoung
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll

# Dark Mode
darkmode: true

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요, 성장하는 것이 즐거운 개발자 <mark>정한영</mark>입니다. 
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
